base_config:     
  output_name: sim_a                          # Simulation identifier name
  scenario: rosslyn                           # scenario name
  yaml_output: true
  logging_level: info                         # logging level: debug, info, warning, error, critical, NONE
  resume: false                               # skip steps already concluded
  clean_previous:                             # remove result folders before running
    #- mobility 
    - rt
    #- db
    #- csv
    #- hdf5
    #- lidar
    #- images

pipeline:
  mobility:
    enabled: true
    tool: sumo                                # null | none
    placement_limits: 
      enabled: false   
      max_lim: [843, 523]                     # [x, y] study area limits for placement of Tx and Rx
      min_lim: [660, 334]                     # [x, y] study area limits for placement of Tx and Rx
  
  ray_tracing:                                # parsing automático
    enabled: true
    #tool: wireless_insite                    # wireless_insite | none
    jump: true

  data_processing:
    enabled: false
    which: selected                               # all | selected
    outputs:                                        # ["db", "coord", "rays"]
      - db                                          # database (sqlite/postgres/hdf5)
      - coord                                       # coordenadas
      - rays
  
  blensor:
    enabled: false 
    enabled: false 
    outputs: 
      - lidar
      - image

  post_processing:
    enabled: false  
    which: selected                               # all | selected
    outputs:                                        # ["beams", "image", "lidar"]
      - beams
      # - image
      # - lidar
  
  validation:
    run_checkup: false

rmt:
  enabled: true                               # false for isolated simulation
  scenes_per_episode: 2 
  time_between_episodes: 35                   # This time needs to be multiple of scene time step
  sampling_parameters: [0, 6, 0.5]            # start, end, time_step
  features:
    fixed_receivers: false  
    vehicles_template: true 

sumo:
  seed: 10  
  bin: /usr/bin/sumo 
  cfg: seasonal

ray_tracing:
  use_pedestrians: false
  use_drone:
    enabled: false
    altitude: 5                       #meters
  receivers_per_episode: 1
  transmitters_per_episode: 1
  v2v:
    enabled: false
    closest_vehicles: # from potential receiver vehicles in area, choose the closest ones to be Rx. 
      enabled: false
      n_of_vehicles: 5 # Overrites receivers_per_episode
  wireless_insite:
    software_path: /home/fritz/RMT/Softwares/Wireless_Insite/remcom
    LICENSE_FILE: REMCOMINC_LICENSE_FILE=2501@10.10.80.6
    base_files_names:
      study_area_name: study
      tx_name: Tx
      rx_name: Rx
      setup_name: model
      vehicles_name: random-line
  
blensor_options:
  path_to_scenario_blend: data/rosslyn/base/blender/rosslyn1.blend
  path_to_vehicles_blend: data/rosslyn/base/blender/vehicles.blend
  path_blensor_image: utils/animation/Blensor-x64.AppImage
  image_options:
    BS_camera: true
    UE_camera: false
    n_camera_BS: 3

post_processing:
  area_of_analyses: # only fill csv with objects within this area
    enabled: false
    limits: [660, 334, 843, 523]              #[x1,y1, x2, y2]

  mimo:
    import_precoding: assets/codebooks/default_mikrotik_cb.npy
    import_channels: false
    import_combining: false
    antenna_array_expansion:
      Tx: [6, 6] #[x, y]
      Rx: [1, 1] #[x, y]
      normalized_antenna_distance: 0.5
    array_rotation:
      Tx: [0,0,0] #[alpha, beta, gamma]
      Rx: [0,0,0] #[alpha, beta, gamma]
    
  cartesian_lidar_matrix:
    coordinate_system: cartesian  #[spherical | cartesian]
    QP: # cartesian
      step: [1.15, 1.25, 1]  # step in x, y, z directions
      min: [744, 429, 0]      # minimum x, y, z coordinates
      max: [767, 679, 10]     # maximum x, y, z coordinates
    QPsph:
      step: [1.15, 1.25, 1]         # step in r, theta, phi directions
      min: [744, 429, 0]
      max: [767, 679, 10]
    Tx_position: [13.735024754781474, 12.543859564388237, 25.0] #[x,y,z]
    max_dist_LIDAR: 100
    type_data: 3D # 2D | 3D