[project]
name = "rmt"
version = "0.1.0"
description = "Raymobtime simulation pipeline"
readme = "README.md"
requires-python = "==3.8.20"
dependencies = [
    "attrdict>=2.0.1",
    "cheetah3>=3.2.6.post1",
    "descartes>=1.1.0",
    "h5py>=3.11.0",
    "matplotlib>=3.7.5",
    "numpy>=1.24.4",
    "opencv-python>=4.13.0.92",
    "pandas>=2.0.3",
    "pyreadline>=2.1",
    "scipy>=1.10.1",
    "setuptools>=75.3.4",
    "shapely>=2.0.7",
    "sqlalchemy>=2.0.49",
    "termcolor>=2.4.0",
    "tqdm>=4.67.3",
    "traci>=1.26.0",
    "typing-extensions>=4.13.2",
    "pyyaml>=6.0.2",
    "psutil>=5.9.8",
    "lzf>=0.1",
    "pypcd4>=1.4.3",
]

[project.scripts]
raymobtime = "src.scripts.config:raymobtime"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.uv]
package = true
