import os
import json
import numpy as np
from src.modules.blensor.blensor_src import export_cam_info
from src.modules.postprocessing import (
    save5gmdata as fgdb, 
    global2pixels, 
    gen_K)
    
def obstruction_flag(c):
    """
    Project receiver and obstacle geometry into camera image coordinates.

    This function loads the Raymobtime database and camera calibration data,
    projects the vertices of scene objects into each configured camera view,
    and separates objects into obstacles, receivers, and receiver objects that
    can also act as obstacles. The projected information is saved to a NumPy
    ``.npz`` file for later obstruction or visibility analysis.

    If the camera information file is not available, the function calls
    ``export_cam_info`` to generate it before processing the scenes.

    Args:
        c: Runtime configuration object generated by the Raymobtime configuration
            system. It must provide the working directory, output name, and the
            information required to locate the simulation database and Blender
            camera metadata.

    Raises:
        FileNotFoundError: If the main simulation data folder does not exist.
        FileNotFoundError: If the database or camera information file cannot be
            found after attempting to generate it.
        KeyError: If required camera calibration fields are missing from the
            camera information file.
    """

    main_folder = os.path.join(c.working_directory, 'sim_data', c.base_config.output_name)
    if not os.path.exists(main_folder):
        raise FileNotFoundError(f"ERROR: folder {main_folder} not found")

    database_path = os.path.join(main_folder, f'{c.base_config.output_name}.db')
    session = fgdb.open_database(database_path)
    objcs = session.query(fgdb.InsiteObject)

    # Check for camera info
    cam_info_path = os.path.join(main_folder, 'blend_info', 'cam_info.json')
    if not os.path.exists(cam_info_path):
        export_cam_info(c) # Export and generate the json file
    with open(cam_info_path, 'r') as file:
        cam_info = json.load(file)
    cams = gen_K(cam_info)


    for ep_i, ep in enumerate(session.query(fgdb.Episode)):
        for sc_i, sc in enumerate(ep.scenes):
            rx_pos = []
            obstacles = []
            rx_obstacles = []
            for obj in sc.objects:
                rx_pos_cam = []
                obstacles_cam = []
                rx_obstacles_cam = []
                for cm in cams:
                    cam_position = np.array([cams[cm]["position"]["x"],
                                            cams[cm]["position"]["y"],
                                            cams[cm]["position"]["z"]])
                    vertices = []
                    for vert in obj.vertice_array:
                        _, pos = global2pixels(vert, 
                                                cam_position,
                                                cams[cm]["rotation_radians"]["z"],
                                                cams[cm]["rotation_radians"]["x"],
                                                cams[cm]["rotation_radians"]["y"],
                                                cams[cm]["K"])
                        vertices.append(pos)
                    
                    if len(obj.receivers) > 0:
                        position = obj.position.copy()
                        position[2] *= 2
                        _, pos = global2pixels(vert, 
                                                cam_position,
                                                cams[cm]["rotation_radians"]["z"],
                                                cams[cm]["rotation_radians"]["x"],
                                                cams[cm]["rotation_radians"]["y"],
                                                cams[cm]["K"])
                        rx_pos_cam.append(pos)
                        rx_obstacles_cam.append(vertices)
                    else:
                        obstacles_cam.append(vertices)
                if len(obj.receivers) > 0:
                    rx_pos.append(rx_pos_cam)
                    rx_obstacles.append(rx_obstacles_cam)
                else:
                    obstacles.append(obstacles_cam)
            obstacles = np.array(obstacles)
            rx_pos = np.array(rx_pos)
            rx_obstacles = np.array(rx_obstacles)
            np.savez('flag_obstruction.npz', receiver_position=rx_pos[0], obstacles=obstacles, receivers_as_obstacles=rx_obstacles[1:])
