'''
This code gets the p2m files generated by InSite via simulation.py and writes in a database called episode.db.
One does not need to specify the number of scenes per episode because this information is obtained from
the JSON file and confirmed (redundancy) with the file 'sumoOutputInfoFileName.txt' at "run_dir".
'''
import os
import json
import numpy as np
import csv
import logging
from src.scripts.helpers import format_run_name
from src.modules.rt.wi.modeling import objects
from src.modules.rt.wi.parsing import P2mPaths
from src.modules.postprocessing import (
    save5gmdata as fgdb,
    save5gmdata_IsolatedSim as fgdbIS,
    sumoOutputFile)

def set_angle_range(angle, range=[180, -180]):
    """
    Normalize an angle to the interval [-180, 180].

    This function adjusts angles outside the range [-180, 180] by adding or
    subtracting 360 degrees. It is mainly used to keep azimuth angles consistent
    after applying vehicle orientation corrections.

    Args:
        angle: Angle in degrees to be normalized.
        range: Angle range reference. This argument is currently unused and kept
            for compatibility with previous versions.

    Returns:
        The normalized angle in degrees.
    """
    if angle<=-180:
        angle+=360
    if angle>180:
        angle-=360
    return angle

def count_model_paths(dir):
    """
    Count Wireless InSite path files in a directory tree.

    This function recursively walks through the given directory and counts all
    files whose names start with ``model.paths``. It is used mainly for isolated
    simulations, where multiple receiver path files may exist in the same
    simulation result folder.

    Args:
        dir: Root directory where Wireless InSite path files should be searched.

    Returns:
        Number of files whose names start with ``model.paths``.

    Raises:
        FileNotFoundError: If the provided directory does not exist.
    """
    c = 0
    base_isolated_sim_dir = os.path.join(dir)

    for _, _, file in os.walk(dir):
        for file in file:
            if file.startswith("model.paths"):
                c += 1
    return c

def gen_database(c):
    """
    Generate a structured SQLite database from Raymobtime simulation outputs.

    This function reads Wireless InSite ray-tracing results, SUMO vehicle
    information, simulation metadata, and object geometry files, then stores the
    processed data in a SQLite database. The database includes episodes, scenes,
    objects, receivers, transmitters, and propagation rays.

    The function supports two execution modes:
        - isolated simulation mode, where receiver ray information is extracted
          directly from isolated Wireless InSite path files;
        - full Raymobtime simulation mode, where each run folder contains object
          files, path files, SUMO output files, and simulation metadata.

    In full simulation mode, the function also corrects arrival and departure
    azimuth angles according to vehicle orientation, stores object geometry and
    positions, links receivers and transmitters to their corresponding objects,
    and appends ray information to each receiver.

    Args:
        c: Runtime configuration object containing simulation paths, output
            folder names, Wireless InSite project metadata, vehicle template
            options, V2V settings, and execution mode flags.

    Returns:
        None. The generated database is written to disk.

    Raises:
        FileNotFoundError: If required simulation files, object files, path files,
            SUMO output files, or metadata files are missing.
        ValueError: If scene ordering, episode information, or object data is
            inconsistent with the expected simulation structure.
        FormatError: If stored geometric arrays do not match the required shape.
    """
    last_simulation_info = None
    simulation_info = None
    database_folder = c.results_dir_postprocessed
    if not os.path.exists(database_folder):
        os.makedirs(database_folder)
    database_path = os.path.join(
        database_folder, 
        f'{c.base_config.output_name}.db')
    if not c.isolated_sim:  
        session = fgdb.create_database(database_path)
    else:
        session = fgdbIS.create_database(database_path)
    # Object which will be modified in the RWI project
    #base_insite_project_path = 'D:/insitedata/insite_new_simuls/'
    #Folder to store each InSite project and its results (will create subfolders for each "run", run0000, run0001, etc.)
    results_dir = c.results_dir

    #if use 3d detaileds models instead of boxes models
    use_template = c.vehicles_template

    #The infos below typically does not change
    if use_template:
        dst_object_file_nameBaseName = "random-line_.object"
    else:
        dst_object_file_nameBaseName = "random-line.object"
    #Ray-tracing output folder (where InSite will store the results (Study Area name)).
    #They will be later copied to the corresponding output folder specified by results_dir
    project_output_dirBaseName = 'study'
    # Name (basename) of the paths file generated in the simulation
    paths_file_name = 'model.paths.t001_01.r002.p2m'
    #Output files, which are written by the Python scripts
    # Name (basename) of the JSON output simulation info file
    simulation_info_file_name = 'wri-simulation.info'
    sumo_file_name = 'sumoOutputInfoFileName.txt'

    sc_i = 0
    ep_i = -1 #it's summed to 1 and we need to start by 0
    episode = None
    run_i = 0

    if c.isolated_sim:
        number_model_paths = count_model_paths(c.isolated_results_dir)

        for i in range(number_model_paths):
            
            paths_file_name = f'model.paths.t001_01.r00{2+i}.p2m' 
            simulation_dir = os.path.join(c.isolated_results_dir)

            abs_paths_file_name = os.path.join(simulation_dir, project_output_dirBaseName, paths_file_name)
            if os.path.exists(abs_paths_file_name) == False:
                logging.warning(
                    '\033[35m'
                    f'Stopping, file not found:\n'
                    '\033[30m'
                    f'   {abs_paths_file_name}'
                    '\033[0m')

            paths = P2mPaths(abs_paths_file_name)

            for rec_idx in range(paths.get_num_receivers()):
                # Insert data
                receiver = fgdbIS.Receiver()
                if paths.get_total_received_power(rec_idx+1) is None:
                    print(f'Receiver {rec_idx+1} doesnt have rays informations.')
                    continue
                else:
                    receiver.total_received_power = paths.get_total_received_power(rec_idx+1)
                    receiver.mean_time_of_arrival=paths.get_mean_time_of_arrival(rec_idx+1)
                    receiver.total_rays = len(paths.get_p_gain_ndarray(rec_idx+1))            
                session.add(receiver)
                session.commit()
                
                rayIndex = 0
                for departure, arrival, path_gain, arrival_time, interactions_list, phase in zip(
                        paths.get_departure_angle_ndarray(rec_idx+1),
                        paths.get_arrival_angle_ndarray(rec_idx+1),
                        paths.get_p_gain_ndarray(rec_idx+1),
                        paths.get_arrival_time_ndarray(rec_idx+1),
                        paths.get_interactions_list(rec_idx+1),
                        paths.get_p_phase_ndarray(rec_idx+1)):
                    
                    ray = fgdbIS.Ray(
                        receiver_id=receiver.id,
                        departure_elevation=departure[0],
                        departure_azimuth=departure[1],
                        arrival_elevation=arrival[0],
                        arrival_azimuth=arrival[1],
                        path_gain=path_gain,
                        time_of_arrival=arrival_time,
                        interactions=str(interactions_list),
                        phase_in_degrees=phase,
                        interactions_positions=str(paths.get_interactions_positions_as_string(rec_idx+1, rayIndex+1))
                    )
                    session.add(ray)
                    rayIndex += 1

                session.commit()

    else:
        while True:
            run_dir = os.path.join(results_dir, format_run_name(run_i))
            object_file_name = os.path.join(
                run_dir, 
                dst_object_file_nameBaseName)
            #rays information but phase
            abs_paths_file_name = os.path.join(
                run_dir, 
                project_output_dirBaseName, 
                paths_file_name)
            if os.path.exists(abs_paths_file_name) == False:
                logging.debug(
                    '\033[36m'
                    f'Stopping, file not found:\n'
                    '\033[30m'
                    f'   {abs_paths_file_name}'
                    '\033[0m')
                break

            abs_simulation_info_file_name = os.path.join(
                run_dir, 
                simulation_info_file_name)
            with open(abs_simulation_info_file_name) as infile:
                simulation_info = json.load(infile)

            abs_sumo_info_file_name = os.path.join(
                run_dir, 
                sumo_file_name)
            sumo_info = sumoOutputFile.read_csv_sumo(abs_sumo_info_file_name)
            
            # start of episode
            if simulation_info['scene_i'] == 0:
                ep_i += 1
                this_scene_i = 0 #reset counter
                if episode is not None:
                    session.add(episode)
                    session.commit()

                #read SUMO information for this scene from text CSV file
                sumoOutputInfoFileName = os.path.join(run_dir,'sumoOutputInfoFileName.txt')
                with open(sumoOutputInfoFileName, 'r') as f:
                    sumoReader = csv.reader(f) 
                    for row in sumoReader:
                        headerItems = row[0].split(',')
                        TsString = headerItems[-1]
                        try:
                            Ts=TsString.split('=')[1]
                            timeString = headerItems[-2]
                            time=timeString.split('=')[1]
                        except IndexError: #old format
                            Ts=0.005 #initialize values
                            time=-1
                        break 
                    for row in sumoReader:
                        thisEpisodeNumber = int(row[0])
                        if thisEpisodeNumber != ep_i:
                            print('ERROR: thisEpisodeNumber != ep_i. They are:', thisEpisodeNumber, 'and', ep_i,
                                'file: ', sumoOutputInfoFileName, 'read:', row)
                            exit(1)
                        break 
                episode = fgdb.Episode(
                    insite_pah=run_dir,
                    sumo_path=sumoOutputInfoFileName,
                    simulation_time_begin=time, #in milliseconds
                    sampling_time=Ts, #in seconds
                )

            if episode is None:
                raise ValueError(f'From file {object_file_name}')

            if simulation_info['scene_i'] != episode.number_of_scenes:
                raise ValueError(f'Expecting {len(episode.number_of_scenes)} found {simulation_info["scene_i"]}')
                

            with open(object_file_name) as infile:
                obj_file = objects.ObjectFile.from_file(infile)
           
            paths = P2mPaths(abs_paths_file_name)
  
            scene = fgdb.Scene()
            # TODO read from InSite
            scene.study_area = ((0, 0, 0), (0, 0, 0))
            
            # This fixes car angle variation for Tx in case of V2V
            if 'Tx_veh' in simulation_info.keys():
                angleTx = sumo_info[simulation_info['Tx_veh'][0]]['angle']
                
            rec_i = 0
            for structure_group in obj_file:
                for structure in structure_group:
                    for sub_structure in structure:
                        object = fgdb.InsiteObject(name=structure.name)
                        object.vertice_array = sub_structure.as_vertice_array()
                        dimension_max = np.max(object.vertice_array, 0)
                        dimension_min = np.min(object.vertice_array, 0)
                        object.dimension = dimension_max - dimension_min
                        object.position = dimension_max - (object.dimension / 2)
                        object_name = structure.name.rstrip()
                        if object_name in sumo_info:
                            object.angle = sumo_info[object_name]['angle']
                            object.height = sumo_info[object_name]['position'][2]
                        else:
                            object.angle = 0
                            object.height = 0
                        if structure.name.rstrip() in simulation_info['veh_with_antenna']:
                            receiver = fgdb.InsiteReceiver()
                            if paths.get_total_received_power(rec_i+1) is not None:
                                receiver.total_received_power = paths.get_total_received_power(rec_i+1)
                                receiver.mean_time_of_arrival=paths.get_mean_time_of_arrival(rec_i+1)
                                receiver.position = object.position

                                rayIndex = 0
                                for departure, arrival, path_gain, arrival_time, interactions_list, phase in zip(
                                        paths.get_departure_angle_ndarray(rec_i+1),
                                        paths.get_arrival_angle_ndarray(rec_i+1),
                                        paths.get_p_gain_ndarray(rec_i+1),
                                        paths.get_arrival_time_ndarray(rec_i+1),
                                        paths.get_interactions_list(rec_i+1),
                                        paths.get_p_phase_ndarray(rec_i+1)):
                                    ray = fgdb.Ray()
                                    # Fix azimuth considering veh angle
                                    arrival[1] = arrival[1] - sumo_info[structure.name.rstrip()]['angle']
                                    arrival[1] = set_angle_range(arrival[1])
                                    if c.V2V:
                                        departure[1] = departure[1] - angleTx
                                        departure[1] = set_angle_range(departure[1])
                                    ray.departure_elevation, ray.departure_azimuth = departure
                                    ray.arrival_elevation, ray.arrival_azimuth = arrival
                                    ray.path_gain = path_gain
                                    ray.time_of_arrival = arrival_time
                                    ray.interactions = interactions_list
                                    ray.phaseInDegrees = phase
                                    #add 1 because paths start from 1 instead of 0
                                    ray.interactionsPositions = paths.get_interactions_positions_as_string(rec_i+1,rayIndex+1)

                                    receiver.rays.append(ray)
                                    rayIndex += 1 #update for next iteration


                            object.receivers.append(receiver)
                            rec_i += 1
                        if c.V2V:
                            if structure.name.rstrip() in simulation_info['Tx_veh']:
                                transmitter = fgdb.InsiteTransmitter()
                                transmitter.position = object.position
                                object.transmitter.append(transmitter)
                    scene.objects.append(object)

            episode.scenes.append(scene)
            logging.debug(
                '\033[36m'
                f'Processed episode: {ep_i:4d} scene: {this_scene_i:2d}, total {sc_i + 1:5d} '
                '\033[0m')
            sc_i += 1
            this_scene_i += 1
            run_i += 1 #increment loop counter

        if episode == None:
            print('Warning: last episode == None')
        else:
            session.add(episode)
            session.commit()
        session.close()
        logging.info(
            '\033[92m'
            f'Processed {run_i} runs'
            '\033[0m')
