base_config:
  scenario: null
  output_name: null
  resume: null
  clean_previous: null
  logging_level: none                       # logging level: debug, info, warning, error, critical

pipeline:
  mobility:
    enabled: null
    tool: null
    placement_limits:
      enabled: null
      max_lim: null
      min_lim: null

  ray_tracing:
    enabled: null
    tool: null
    jump: null

  post_processing:
    enabled: null
    which: null
    outputs: null

  blensor:
    enabled: null
    outputs: null

  validation:
    run_checkup: null

rmt:
  enabled: null
  sampling_parameters: null
  scenes_per_episode: null
  time_between_episodes: null
  features:
    fixed_receivers: null
    vehicles_template: null

sumo:
  bin: null
  cfg: null
  seed: null

ray_tracing:
  use_pedestrians: null
  use_drone: null
  receivers_per_episode: null
  transmitters_per_episode: null
  v2v:
    enabled: null
    closest_vehicles: 
      enabled: null
      n_of_vehicles: null
    #chose_vehicle: not implemented at all
    #  enabled: false
    #  chosen: Truck
  wireless_insite:
    software_paths: null
    LICENSE_FILE: null
    base_files_names:
      study_area_name: null
      tx_name: null
      rx_name: null
      setup_name: null
      vehicles_name: null

blensor_options:
  path_to_scenario_blend: null
  path_blensor_image: null
  path_to_vehicles_blend: null
  image_options:
    BS_camera: null
    UE_camera: null
    n_camera_BS: null

post_processing:
  area_of_analyses:
    enabled: null
    limits: null

  cartesian_lidar_matrix:
    coordinate_system: null
    QP: null
    QPsph: null
    Tx_position: null
    max_dist_LIDAR: null
    type_data: null

  mimo:
    import_precoding: null
    import_channels: null
    import_combining: null
    antenna_array_expansion:
      normalized_antenna_distance: null
    array_rotation: null